    version: '3.5'
    
    services:
      postgres:
        image: postgres:latest # ultima versão do postgres
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
        ports:
          - "5432:5432" 
        networks:
          - postgres
       # restart: unless-stopped # se ele for parae, ele volta automaticamente, a não ser que seja por um stop
    
      pgadmin:
        image: dpage/pgadmin4 # pg admom na web
        environment:
          PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        ports:
          - "8081:80" # http://localhost:8081/
        depends_on:
          - postgres
        networks:
          - postgres
    
    networks:
      postgres:
        driver: bridge
    
    volumes:
        postgres:
